// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../index.js";

/**
 * A paginated list of calls.
 */
export interface CallList {
    /** String representing the object's type. Always has the value `list`. */
    type?: string;
    /** A list of calls. */
    data?: Intercom.unstable.Call[];
    /** Total number of items available. */
    total_count?: number;
    pages?: Intercom.unstable.CursorPages;
}
