// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../index.js";

export type EventDetails =
    | Intercom.unstable.ConversationAttributeUpdatedByWorkflow
    | Intercom.unstable.ConversationAttributeUpdatedByAdmin
    | Intercom.unstable.CustomActionStarted
    | Intercom.unstable.CustomActionFinished
    | Intercom.unstable.OperatorWorkflowEvent;
