// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../index.js";

/**
 * This will return a list of internal articles for the App.
 */
export interface InternalArticleList {
    /** The type of the object - `list`. */
    type?: "list";
    pages?: Intercom.unstable.CursorPages;
    /** A count of the total number of internal articles. */
    total_count?: number;
    /** An array of Internal Article objects */
    data?: Intercom.unstable.InternalArticleListItem[];
}
