// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         custom_object_type_identifier: "Order",
 *         external_id: "123",
 *         external_created_at: 1392036272,
 *         external_updated_at: 1392036272,
 *         custom_attributes: {
 *             "order_number": "ORDER-12345",
 *             "total_amount": "custom_attributes"
 *         }
 *     }
 */
export interface CreateOrUpdateCustomObjectInstanceRequest {
    /** The unique identifier of the custom object type that defines the structure of the custom object instance. */
    custom_object_type_identifier: string;
    /** A unique identifier for the Custom Object instance in the external system it originated from. */
    external_id?: string;
    /** The time when the Custom Object instance was created in the external system it originated from. */
    external_created_at?: number;
    /** The time when the Custom Object instance was last updated in the external system it originated from. */
    external_updated_at?: number;
    /** The custom attributes which are set for the Custom Object instance. */
    custom_attributes?: Record<string, string | undefined>;
}
