// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         scroll_param: "scroll_param"
 *     }
 */
export interface ScrollOverAllCompaniesRequest {
    /** */
    scroll_param?: string;
}
