/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ScrollOverAllCompaniesRequest {
    /**
     *
     */
    scroll_param?: string;
}
