/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         tag_id: "123"
 *     }
 */
export interface DeleteTagRequest {
    /**
     * The unique identifier of a given tag
     */
    tag_id: string;
}
