// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Intercom from "../../../../../index.js";

export declare namespace ConversationsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Everything about your Conversations
 */
export class ConversationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConversationsClient.Options>;

    constructor(options: ConversationsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * You can fetch a list of all conversations.
     *
     * You can optionally request the result page size and the cursor to start after to fetch the result.
     * {% admonition type="warning" name="Pagination" %}
     *   You can use pagination to limit the number of results returned. The default is `20` results per page.
     *   See the [pagination section](https://developers.intercom.com/docs/build-an-integration/learn-more/rest-apis/pagination/#pagination-for-list-apis) for more details on how to use the `starting_after` param.
     * {% /admonition %}
     *
     * @param {Intercom.preview.ListConversationsRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     *
     * @example
     *     await client.preview.conversations.listConversations({
     *         per_page: 1,
     *         starting_after: "starting_after"
     *     })
     */
    public listConversations(
        request: Intercom.preview.ListConversationsRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.ConversationList> {
        return core.HttpResponsePromise.fromPromise(this.__listConversations(request, requestOptions));
    }

    private async __listConversations(
        request: Intercom.preview.ListConversationsRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.ConversationList>> {
        const { per_page: perPage, starting_after: startingAfter } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (perPage != null) {
            _queryParams.per_page = perPage.toString();
        }

        if (startingAfter != null) {
            _queryParams.starting_after = startingAfter;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                "conversations",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.ConversationList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/conversations");
    }

    /**
     * You can create a conversation that has been initiated by a contact (ie. user or lead).
     * The conversation can be an in-app message only.
     *
     * {% admonition type="info" name="Sending for visitors" %}
     * You can also send a message from a visitor by specifying their `user_id` or `id` value in the `from` field, along with a `type` field value of `contact`.
     * This visitor will be automatically converted to a contact with a lead role once the conversation is created.
     * {% /admonition %}
     *
     * This will return the Message model that has been created.
     *
     *
     * @param {Intercom.preview.CreateConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.createConversation({
     *         from: {
     *             type: "user",
     *             id: "6762f11b1bb69f9f2193bba3"
     *         },
     *         body: "Hello there"
     *     })
     *
     * @example
     *     await client.preview.conversations.createConversation({
     *         from: {
     *             type: "user",
     *             id: "123_doesnt_exist"
     *         },
     *         body: "Hello there"
     *     })
     */
    public createConversation(
        request: Intercom.preview.CreateConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Message> {
        return core.HttpResponsePromise.fromPromise(this.__createConversation(request, requestOptions));
    }

    private async __createConversation(
        request: Intercom.preview.CreateConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Message>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                "conversations",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Message, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations");
    }

    /**
     *
     * You can fetch the details of a single conversation.
     *
     * This will return a single Conversation model with all its conversation parts.
     *
     * {% admonition type="warning" name="Hard limit of 500 parts" %}
     * The maximum number of conversation parts that can be returned via the API is 500. If you have more than that we will return the 500 most recent conversation parts.
     * {% /admonition %}
     *
     * For AI agent conversation metadata, please note that you need to have the agent enabled in your workspace, which is a [paid feature](https://www.intercom.com/help/en/articles/8205718-fin-resolutions#h_97f8c2e671).
     *
     * @param {Intercom.preview.RetrieveConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.retrieveConversation({
     *         id: 1,
     *         display_as: "plaintext",
     *         include_translations: true,
     *         include_email_history: true
     *     })
     */
    public retrieveConversation(
        request: Intercom.preview.RetrieveConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Conversation> {
        return core.HttpResponsePromise.fromPromise(this.__retrieveConversation(request, requestOptions));
    }

    private async __retrieveConversation(
        request: Intercom.preview.RetrieveConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Conversation>> {
        const {
            id,
            display_as: displayAs,
            include_translations: includeTranslations,
            include_email_history: includeEmailHistory,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (displayAs != null) {
            _queryParams.display_as = displayAs;
        }

        if (includeTranslations != null) {
            _queryParams.include_translations = includeTranslations.toString();
        }

        if (includeEmailHistory != null) {
            _queryParams.include_email_history = includeEmailHistory.toString();
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Conversation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/conversations/{id}");
    }

    /**
     *
     * You can update an existing conversation.
     *
     * {% admonition type="info" name="Replying and other actions" %}
     * If you want to reply to a coveration or take an action such as assign, unassign, open, close or snooze, take a look at the reply and manage endpoints.
     * {% /admonition %}
     *
     * {% admonition type="info" %}
     *   This endpoint handles both **conversation updates** and **custom object associations**.
     *
     *   See _`update a conversation with an association to a custom object instance`_ in the request/response examples to see the custom object association format.
     * {% /admonition %}
     *
     *
     * @param {Intercom.preview.UpdateConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.updateConversation({
     *         id: 1,
     *         display_as: "plaintext",
     *         read: true,
     *         title: "new conversation title",
     *         custom_attributes: {
     *             "issue_type": "Billing",
     *             "priority": "High"
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.updateConversation({
     *         id: 1,
     *         display_as: "plaintext",
     *         custom_attributes: {
     *             "order": {}
     *         }
     *     })
     */
    public updateConversation(
        request: Intercom.preview.UpdateConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Conversation> {
        return core.HttpResponsePromise.fromPromise(this.__updateConversation(request, requestOptions));
    }

    private async __updateConversation(
        request: Intercom.preview.UpdateConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Conversation>> {
        const { id, display_as: displayAs, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (displayAs != null) {
            _queryParams.display_as = displayAs;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Conversation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/conversations/{id}");
    }

    /**
     * {% admonition type="warning" name="Irreversible operation" %}
     * Deleting a conversation is permanent and cannot be reversed.
     * {% /admonition %}
     *
     * You can delete a single conversation. The behavior depends on the `retain_metrics` parameter:
     *
     * - **With `retain_metrics=true` (default)**: Deletes the conversation while retaining reporting data. The conversation will still appear in reporting, though some data may be incomplete due to the deletion.
     *
     * - **With `retain_metrics=false`**: Deletes the conversation and all associated reporting data. The conversation will be completely removed from both the inbox and all reporting.
     *
     * {% admonition type="info" name="Required scope for retain_metrics=false" %}
     * Using `retain_metrics=false` requires the `delete_conversations_and_metrics` OAuth scope.
     * {% /admonition %}
     *
     * For more info, see [this help center article](https://www.intercom.com/help/en/articles/13885146-deleting-a-conversation).
     *
     * @param {Intercom.preview.DeleteConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     *
     * @example
     *     await client.preview.conversations.deleteConversation({
     *         id: 1,
     *         retain_metrics: true
     *     })
     */
    public deleteConversation(
        request: Intercom.preview.DeleteConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.ConversationDeleted> {
        return core.HttpResponsePromise.fromPromise(this.__deleteConversation(request, requestOptions));
    }

    private async __deleteConversation(
        request: Intercom.preview.DeleteConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.ConversationDeleted>> {
        const { id, retain_metrics: retainMetrics } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (retainMetrics != null) {
            _queryParams.retain_metrics = retainMetrics.toString();
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.ConversationDeleted, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/conversations/{id}");
    }

    /**
     * You can search for multiple conversations by the value of their attributes in order to fetch exactly which ones you want.
     *
     * To search for conversations, you need to send a `POST` request to `https://api.intercom.io/conversations/search`.
     *
     * This will accept a query object in the body which will define your filters in order to search for conversations.
     * {% admonition type="warning" name="Optimizing search queries" %}
     *   Search queries can be complex, so optimizing them can help the performance of your search.
     *   Use the `AND` and `OR` operators to combine multiple filters to get the exact results you need and utilize
     *   pagination to limit the number of results returned. The default is `20` results per page and maximum is `150`.
     *   See the [pagination section](https://developers.intercom.com/docs/build-an-integration/learn-more/rest-apis/pagination/#example-search-conversations-request) for more details on how to use the `starting_after` param.
     * {% /admonition %}
     *
     * ### Nesting & Limitations
     *
     * You can nest these filters in order to get even more granular insights that pinpoint exactly what you need. Example: (1 OR 2) AND (3 OR 4).
     * There are some limitations to the amount of multiple's there can be:
     * - There's a limit of max 2 nested filters
     * - There's a limit of max 15 filters for each AND or OR group
     *
     * ### Accepted Fields
     *
     * Most keys listed in the conversation model are searchable, whether writeable or not. The value you search for has to match the accepted type, otherwise the query will fail (ie. as `created_at` accepts a date, the `value` cannot be a string such as `"foorbar"`).
     * The `source.body` field is unique as the search will not be performed against the entire value, but instead against every element of the value separately. For example, when searching for a conversation with a `"I need support"` body - the query should contain a `=` operator with the value `"support"` for such conversation to be returned. A query with a `=` operator and a `"need support"` value will not yield a result.
     *
     * | Field                                     | Type                                                                                                                                                   |
     * | :---------------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------- |
     * | id                                        | String                                                                                                                                                 |
     * | created_at                                | Date (UNIX timestamp)                                                                                                                                  |
     * | updated_at                                | Date (UNIX timestamp)                                                                                                                                  |
     * | source.type                               | String<br>Accepted fields are `conversation`, `email`, `facebook`, `instagram`, `phone_call`, `phone_switch`, `push`, `sms`, `twitter` and `whatsapp`. |
     * | source.id                                 | String                                                                                                                                                 |
     * | source.delivered_as                       | String                                                                                                                                                 |
     * | source.subject                            | String                                                                                                                                                 |
     * | source.body                               | String                                                                                                                                                 |
     * | source.author.id                          | String                                                                                                                                                 |
     * | source.author.type                        | String                                                                                                                                                 |
     * | source.author.name                        | String                                                                                                                                                 |
     * | source.author.email                       | String                                                                                                                                                 |
     * | source.url                                | String                                                                                                                                                 |
     * | contact_ids                               | String                                                                                                                                                 |
     * | teammate_ids                              | String                                                                                                                                                 |
     * | admin_assignee_id                         | Integer                                                                                                                                                |
     * | team_assignee_id                          | Integer                                                                                                                                                |
     * | channel_initiated                         | String                                                                                                                                                 |
     * | open                                      | Boolean                                                                                                                                                |
     * | read                                      | Boolean                                                                                                                                                |
     * | state                                     | String                                                                                                                                                 |
     * | waiting_since                             | Date (UNIX timestamp)                                                                                                                                  |
     * | snoozed_until                             | Date (UNIX timestamp)                                                                                                                                  |
     * | tag_ids                                   | String                                                                                                                                                 |
     * | priority                                  | String                                                                                                                                                 |
     * | statistics.time_to_assignment             | Integer                                                                                                                                                |
     * | statistics.time_to_admin_reply            | Integer                                                                                                                                                |
     * | statistics.time_to_first_close            | Integer                                                                                                                                                |
     * | statistics.time_to_last_close             | Integer                                                                                                                                                |
     * | statistics.median_time_to_reply           | Integer                                                                                                                                                |
     * | statistics.first_contact_reply_at         | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.first_assignment_at            | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.first_admin_reply_at           | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.first_close_at                 | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.last_assignment_at             | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.last_assignment_admin_reply_at | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.last_contact_reply_at          | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.last_admin_reply_at            | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.last_close_at                  | Date (UNIX timestamp)                                                                                                                                  |
     * | statistics.last_closed_by_id              | String                                                                                                                                                 |
     * | statistics.count_reopens                  | Integer                                                                                                                                                |
     * | statistics.count_assignments              | Integer                                                                                                                                                |
     * | statistics.count_conversation_parts       | Integer                                                                                                                                                |
     * | conversation_rating.requested_at          | Date (UNIX timestamp)                                                                                                                                  |
     * | conversation_rating.replied_at            | Date (UNIX timestamp)                                                                                                                                  |
     * | conversation_rating.score                 | Integer                                                                                                                                                |
     * | conversation_rating.remark                | String                                                                                                                                                 |
     * | conversation_rating.contact_id            | String                                                                                                                                                 |
     * | conversation_rating.admin_d               | String                                                                                                                                                 |
     * | ai_agent_participated                     | Boolean                                                                                                                                                |
     * | ai_agent.resolution_state                 | String                                                                                                                                                 |
     * | ai_agent.last_answer_type                 | String                                                                                                                                                 |
     * | ai_agent.rating                           | Integer                                                                                                                                                |
     * | ai_agent.rating_remark                    | String                                                                                                                                                 |
     * | ai_agent.source_type                      | String                                                                                                                                                 |
     * | ai_agent.source_title                     | String                                                                                                                                                 |
     *
     * ### Accepted Operators
     *
     * The table below shows the operators you can use to define how you want to search for the value.  The operator should be put in as a string (`"="`). The operator has to be compatible with the field's type  (eg. you cannot search with `>` for a given string value as it's only compatible for integer's and dates).
     *
     * | Operator | Valid Types                    | Description                                                  |
     * | :------- | :----------------------------- | :----------------------------------------------------------- |
     * | =        | All                            | Equals                                                       |
     * | !=       | All                            | Doesn't Equal                                                |
     * | IN       | All                            | In  Shortcut for `OR` queries  Values most be in Array       |
     * | NIN      | All                            | Not In  Shortcut for `OR !` queries  Values must be in Array |
     * | >        | Integer  Date (UNIX Timestamp) | Greater (or equal) than                                      |
     * | <       | Integer  Date (UNIX Timestamp) | Lower (or equal) than                                        |
     * | ~        | String                         | Contains                                                     |
     * | !~       | String                         | Doesn't Contain                                              |
     * | ^        | String                         | Starts With                                                  |
     * | $        | String                         | Ends With                                                    |
     *
     * @param {Intercom.preview.SearchRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.preview.conversations.searchConversations({
     *         query: {
     *             operator: "AND",
     *             value: [{
     *                     field: "created_at",
     *                     operator: ">",
     *                     value: "1306054154"
     *                 }]
     *         },
     *         pagination: {
     *             per_page: 5
     *         }
     *     })
     */
    public searchConversations(
        request: Intercom.preview.SearchRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.ConversationList> {
        return core.HttpResponsePromise.fromPromise(this.__searchConversations(request, requestOptions));
    }

    private async __searchConversations(
        request: Intercom.preview.SearchRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.ConversationList>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                "conversations/search",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.ConversationList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.IntercomError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/search");
    }

    /**
     * You can reply to a conversation with a message from an admin or on behalf of a contact, or with a note for admins.
     *
     * @param {Intercom.preview.ReplyConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.replyConversation({
     *         id: "123 or \"last\"",
     *         body: {
     *             message_type: "comment",
     *             type: "user",
     *             body: "Thanks again :)",
     *             intercom_user_id: "6762f1571bb69f9f2193bbbb"
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.replyConversation({
     *         id: "123 or \"last\"",
     *         body: {
     *             message_type: "note",
     *             type: "admin",
     *             body: "<html> <body>  <h2>An Unordered HTML List</h2>  <ul>   <li>Coffee</li>   <li>Tea</li>   <li>Milk</li> </ul>    <h2>An Ordered HTML List</h2>  <ol>   <li>Coffee</li>   <li>Tea</li>   <li>Milk</li> </ol>   </body> </html>",
     *             admin_id: "3156780"
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.replyConversation({
     *         id: "123 or \"last\"",
     *         body: {
     *             message_type: "quick_reply",
     *             type: "admin",
     *             admin_id: "3156780",
     *             reply_options: [{
     *                     text: "Yes",
     *                     uuid: "a5e1c524-5ddd-4c3e-9328-6bca5d6e3edb"
     *                 }, {
     *                     text: "No",
     *                     uuid: "f4a98af1-be56-4948-a57e-e1a83f8484c6"
     *                 }]
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.replyConversation({
     *         id: "123 or \"last\"",
     *         body: {
     *             message_type: "comment",
     *             type: "user",
     *             body: "body",
     *             reply_options: [{
     *                     text: "Yes",
     *                     uuid: "a5e1c524-5ddd-4c3e-9328-6bca5d6e3edb"
     *                 }],
     *             intercom_user_id: "6762f1621bb69f9f2193bbbe"
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.replyConversation({
     *         id: "123 or \"last\"",
     *         body: {
     *             message_type: "comment",
     *             type: "user",
     *             body: "Thanks again :)",
     *             intercom_user_id: "6762f1661bb69f9f2193bbbf"
     *         }
     *     })
     */
    public replyConversation(
        request: Intercom.preview.ReplyConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Conversation> {
        return core.HttpResponsePromise.fromPromise(this.__replyConversation(request, requestOptions));
    }

    private async __replyConversation(
        request: Intercom.preview.ReplyConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Conversation>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}/reply`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Conversation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/{id}/reply");
    }

    /**
     * For managing conversations you can:
     * - Close a conversation
     * - Snooze a conversation to reopen on a future date
     * - Open a conversation which is `snoozed` or `closed`
     * - Assign a conversation to an admin and/or team.
     *
     * @param {Intercom.preview.ManageConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.manageConversation({
     *         id: "123",
     *         body: {
     *             message_type: "close",
     *             type: "admin",
     *             admin_id: "12345"
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.manageConversation({
     *         id: "123",
     *         body: {
     *             message_type: "snoozed",
     *             admin_id: "5017691",
     *             snoozed_until: 1673609604
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.manageConversation({
     *         id: "123",
     *         body: {
     *             message_type: "open",
     *             admin_id: "5017690"
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.manageConversation({
     *         id: "123",
     *         body: {
     *             message_type: "assignment",
     *             type: "admin",
     *             admin_id: "12345",
     *             assignee_id: "4324241"
     *         }
     *     })
     */
    public manageConversation(
        request: Intercom.preview.ManageConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Conversation> {
        return core.HttpResponsePromise.fromPromise(this.__manageConversation(request, requestOptions));
    }

    private async __manageConversation(
        request: Intercom.preview.ManageConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Conversation>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}/parts`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Conversation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/{id}/parts");
    }

    /**
     * You can update properties of a conversation part. Currently supports updating the send state of an external reply or marking a part as seen by an admin.
     *
     * {% admonition type="warning" name="Experimental" %}
     *   This is an experimental endpoint. It requires a valid HMAC secret for authentication in addition to the standard bearer token.
     * {% /admonition %}
     *
     * @param {Intercom.preview.UpdateConversationPartRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.updateConversationPart({
     *         conversation_id: "123",
     *         id: "456",
     *         send_state: "sent",
     *         info_message: "Message delivered successfully",
     *         experimental: true,
     *         secret: "hmac_secret_value"
     *     })
     *
     * @example
     *     await client.preview.conversations.updateConversationPart({
     *         conversation_id: "123",
     *         id: "456",
     *         seen: true,
     *         admin_id: "991267694",
     *         experimental: true,
     *         secret: "hmac_secret_value"
     *     })
     */
    public updateConversationPart(
        request: Intercom.preview.UpdateConversationPartRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.ConversationPart> {
        return core.HttpResponsePromise.fromPromise(this.__updateConversationPart(request, requestOptions));
    }

    private async __updateConversationPart(
        request: Intercom.preview.UpdateConversationPartRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.ConversationPart>> {
        const { conversation_id: conversationId, id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(conversationId)}/conversation_parts/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.ConversationPart, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/conversations/{conversation_id}/conversation_parts/{id}",
        );
    }

    /**
     * You can add participants who are contacts to a conversation, on behalf of either another contact or an admin.
     *
     * {% admonition type="warning" name="Contacts without an email" %}
     * If you add a contact via the email parameter and there is no user/lead found on that workspace with he given email, then we will create a new contact with `role` set to `lead`.
     * {% /admonition %}
     *
     *
     * @param {Intercom.preview.AttachContactToConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.attachContactToConversation({
     *         id: "123",
     *         admin_id: "12345",
     *         customer: {
     *             intercom_user_id: "6762f19b1bb69f9f2193bbd4"
     *         }
     *     })
     *
     * @example
     *     await client.preview.conversations.attachContactToConversation({
     *         id: "123",
     *         admin_id: "12345",
     *         customer: {
     *             intercom_user_id: "6762f19e1bb69f9f2193bbd5"
     *         }
     *     })
     */
    public attachContactToConversation(
        request: Intercom.preview.AttachContactToConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Conversation> {
        return core.HttpResponsePromise.fromPromise(this.__attachContactToConversation(request, requestOptions));
    }

    private async __attachContactToConversation(
        request: Intercom.preview.AttachContactToConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Conversation>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}/customers`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Conversation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/conversations/{id}/customers",
        );
    }

    /**
     * You can add participants who are contacts to a conversation, on behalf of either another contact or an admin.
     *
     * {% admonition type="warning" name="Contacts without an email" %}
     * If you add a contact via the email parameter and there is no user/lead found on that workspace with he given email, then we will create a new contact with `role` set to `lead`.
     * {% /admonition %}
     *
     *
     * @param {Intercom.preview.DetachContactFromConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.ForbiddenError}
     * @throws {@link Intercom.preview.NotFoundError}
     * @throws {@link Intercom.preview.UnprocessableEntityError}
     *
     * @example
     *     await client.preview.conversations.detachContactFromConversation({
     *         conversation_id: "123",
     *         contact_id: "123",
     *         admin_id: "5017690"
     *     })
     */
    public detachContactFromConversation(
        request: Intercom.preview.DetachContactFromConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Conversation> {
        return core.HttpResponsePromise.fromPromise(this.__detachContactFromConversation(request, requestOptions));
    }

    private async __detachContactFromConversation(
        request: Intercom.preview.DetachContactFromConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Conversation>> {
        const { conversation_id: conversationId, contact_id: contactId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(conversationId)}/customers/${core.url.encodePathParam(contactId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Conversation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Intercom.preview.ForbiddenError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Intercom.preview.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/conversations/{conversation_id}/customers/{contact_id}",
        );
    }

    /**
     * List all pause/resume events for a conversation. These events track when teammates paused or resumed handling a conversation.
     *
     * Requires the `read_conversations` OAuth scope.
     *
     * @param {Intercom.preview.ListHandlingEventsRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.listHandlingEvents({
     *         id: "123"
     *     })
     */
    public listHandlingEvents(
        request: Intercom.preview.ListHandlingEventsRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.HandlingEventList> {
        return core.HttpResponsePromise.fromPromise(this.__listHandlingEvents(request, requestOptions));
    }

    private async __listHandlingEvents(
        request: Intercom.preview.ListHandlingEventsRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.HandlingEventList>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}/handling_events`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.HandlingEventList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/conversations/{id}/handling_events",
        );
    }

    /**
     * List side conversations for a given conversation. Side conversations are internal threads created by teammates from within a conversation.
     *
     * Each side conversation includes its conversation parts (messages). Results are paginated.
     *
     * Requires the `read_conversations` OAuth scope.
     *
     * @param {Intercom.preview.ListSideConversationsRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.listSideConversations({
     *         id: "123",
     *         page: 1,
     *         per_page: 1
     *     })
     */
    public listSideConversations(
        request: Intercom.preview.ListSideConversationsRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.SideConversationList> {
        return core.HttpResponsePromise.fromPromise(this.__listSideConversations(request, requestOptions));
    }

    private async __listSideConversations(
        request: Intercom.preview.ListSideConversationsRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.SideConversationList>> {
        const { id, page, per_page: perPage } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (perPage != null) {
            _queryParams.per_page = perPage.toString();
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}/side_conversations`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Intercom.preview.SideConversationList,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/conversations/{id}/side_conversations",
        );
    }

    /**
     * You can redact a conversation part or the source message of a conversation (as seen in the source object).
     *
     * {% admonition type="info" name="Redacting parts and messages" %}
     * If you are redacting a conversation part, it must have a `body`. If you are redacting a source message, it must have been created by a contact. We will return a `conversation_part_not_redactable` error if these criteria are not met.
     * {% /admonition %}
     *
     *
     * @param {Intercom.preview.RedactConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.conversations.redactConversation({
     *         type: "conversation_part",
     *         conversation_id: "19894788788",
     *         conversation_part_id: "19381789428"
     *     })
     *
     * @example
     *     await client.preview.conversations.redactConversation({
     *         type: "conversation_part",
     *         conversation_id: "really_123_doesnt_exist",
     *         conversation_part_id: "really_123_doesnt_exist"
     *     })
     */
    public redactConversation(
        request: Intercom.preview.RedactConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Conversation> {
        return core.HttpResponsePromise.fromPromise(this.__redactConversation(request, requestOptions));
    }

    private async __redactConversation(
        request: Intercom.preview.RedactConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Conversation>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                "conversations/redact",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Conversation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/redact");
    }

    /**
     * You can convert a conversation to a ticket.
     *
     * @param {Intercom.preview.ConvertConversationToTicketRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.BadRequestError}
     *
     * @example
     *     await client.preview.conversations.convertConversationToTicket({
     *         id: 1,
     *         ticket_type_id: "53"
     *     })
     *
     * @example
     *     await client.preview.conversations.convertConversationToTicket({
     *         id: 1,
     *         ticket_type_id: "54"
     *     })
     */
    public convertConversationToTicket(
        request: Intercom.preview.ConvertConversationToTicketRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.Ticket | undefined> {
        return core.HttpResponsePromise.fromPromise(this.__convertConversationToTicket(request, requestOptions));
    }

    private async __convertConversationToTicket(
        request: Intercom.preview.ConvertConversationToTicketRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.Ticket | undefined>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `conversations/${core.url.encodePathParam(id)}/convert`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.Ticket | undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Intercom.preview.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/{id}/convert");
    }

    /**
     * List all deleted conversation IDs.
     *
     * {% admonition type="warning" name="Pagination" %}
     *   You can use pagination to limit the number of results returned. The default is `20` results per page. You can navigate to next pages using the `page` param.
     * {% /admonition %}
     *
     * @param {Intercom.preview.ListDeletedConversationIdsRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.BadRequestError}
     * @throws {@link Intercom.preview.UnauthorizedError}
     *
     * @example
     *     await client.preview.conversations.listDeletedConversationIds({
     *         page: 1,
     *         per_page: 1,
     *         order: "desc"
     *     })
     */
    public listDeletedConversationIds(
        request: Intercom.preview.ListDeletedConversationIdsRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DeletedConversationList> {
        return core.HttpResponsePromise.fromPromise(this.__listDeletedConversationIds(request, requestOptions));
    }

    private async __listDeletedConversationIds(
        request: Intercom.preview.ListDeletedConversationIdsRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DeletedConversationList>> {
        const { page, per_page: perPage, order } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (perPage != null) {
            _queryParams.per_page = perPage.toString();
        }

        if (order != null) {
            _queryParams.order = order;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                "conversations/deleted",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Intercom.preview.DeletedConversationList,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Intercom.preview.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/conversations/deleted");
    }
}
