/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../index";

export interface AttachContactToConversationRequestCustomerIntercomUserId {
    /** The identifier for the contact as given by Intercom. */
    intercom_user_id: string;
    customer?: Intercom.CustomerRequest;
}
