/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The state of the ticket.
 */
export type TicketPartTicketState = "submitted" | "in_progress" | "waiting_on_customer" | "resolved";

export const TicketPartTicketState = {
    Submitted: "submitted",
    InProgress: "in_progress",
    WaitingOnCustomer: "waiting_on_customer",
    Resolved: "resolved",
} as const;
