/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../index";

export type TicketsReplyRequestBody = Intercom.ContactReplyTicketRequest | Intercom.AdminReplyTicketRequest;
