// This file was auto-generated by Fern from our API Definition.

export const RetrieveDataConnectorRequestStateVersion = {
    Draft: "draft",
    Live: "live",
} as const;
export type RetrieveDataConnectorRequestStateVersion =
    (typeof RetrieveDataConnectorRequestStateVersion)[keyof typeof RetrieveDataConnectorRequestStateVersion];
