// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Intercom from "../../../../../index.js";

export declare namespace DataConnectorsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Everything about your Data Connectors
 */
export class DataConnectorsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DataConnectorsClient.Options>;

    constructor(options: DataConnectorsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a paginated list of all data connectors for the workspace, ordered by most recently updated first. Data connectors allow workflows and AI agents to make HTTP requests to external APIs.
     *
     * @param {Intercom.preview.ListDataConnectorsRequest} request
     * @param {DataConnectorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.BadRequestError}
     * @throws {@link Intercom.preview.UnauthorizedError}
     *
     * @example
     *     await client.preview.dataConnectors.listDataConnectors({
     *         per_page: 1,
     *         starting_after: "starting_after"
     *     })
     */
    public listDataConnectors(
        request: Intercom.preview.ListDataConnectorsRequest = {},
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DataConnectorList> {
        return core.HttpResponsePromise.fromPromise(this.__listDataConnectors(request, requestOptions));
    }

    private async __listDataConnectors(
        request: Intercom.preview.ListDataConnectorsRequest = {},
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DataConnectorList>> {
        const { per_page: perPage, starting_after: startingAfter } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (perPage != null) {
            _queryParams.per_page = perPage.toString();
        }

        if (startingAfter != null) {
            _queryParams.starting_after = startingAfter;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                "data_connectors",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.DataConnectorList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Intercom.preview.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/data_connectors");
    }

    /**
     * Create a new data connector. The connector is created in `draft` state. Configure its URL, headers, data inputs, and other settings, then set it to `live` when ready.
     *
     * @param {Intercom.preview.CreateDataConnectorRequest} request
     * @param {DataConnectorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.UnprocessableEntityError}
     *
     * @example
     *     await client.preview.dataConnectors.createDataConnector({
     *         name: "Get Order Status",
     *         description: "Looks up order status from an external service",
     *         http_method: "get",
     *         url: "https://api.example.com/orders/{{order_id}}/status",
     *         direct_fin_usage: true,
     *         audiences: ["leads", "visitors"],
     *         headers: [{
     *                 name: "Content-Type",
     *                 value: "application/json"
     *             }],
     *         data_inputs: [{
     *                 name: "order_id",
     *                 type: "string",
     *                 description: "The order ID to look up",
     *                 required: true,
     *                 default_value: ""
     *             }],
     *         customer_authentication: true,
     *         bypass_authentication: false,
     *         validate_missing_attributes: true
     *     })
     *
     * @example
     *     await client.preview.dataConnectors.createDataConnector({
     *         name: "My Connector"
     *     })
     *
     * @example
     *     await client.preview.dataConnectors.createDataConnector({
     *         name: "Order Lookup",
     *         mock_response: {
     *             "order": {
     *                 "id": 12345,
     *                 "status": "shipped"
     *             }
     *         }
     *     })
     */
    public createDataConnector(
        request: Intercom.preview.CreateDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DataConnectorDetail> {
        return core.HttpResponsePromise.fromPromise(this.__createDataConnector(request, requestOptions));
    }

    private async __createDataConnector(
        request: Intercom.preview.CreateDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DataConnectorDetail>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                "data_connectors",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.DataConnectorDetail, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Intercom.preview.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/data_connectors");
    }

    /**
     * You can retrieve the full detail of a single data connector by its ID.
     *
     * The response includes configuration, data inputs, response fields, and object mappings.
     *
     * @param {Intercom.preview.RetrieveDataConnectorRequest} request
     * @param {DataConnectorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.BadRequestError}
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.dataConnectors.retrieveDataConnector({
     *         id: "12345",
     *         state_version: "draft"
     *     })
     */
    public retrieveDataConnector(
        request: Intercom.preview.RetrieveDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DataConnectorDetail> {
        return core.HttpResponsePromise.fromPromise(this.__retrieveDataConnector(request, requestOptions));
    }

    private async __retrieveDataConnector(
        request: Intercom.preview.RetrieveDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DataConnectorDetail>> {
        const { id, state_version: stateVersion } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (stateVersion != null) {
            _queryParams.state_version = stateVersion;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `data_connectors/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.DataConnectorDetail, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Intercom.preview.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/data_connectors/{id}");
    }

    /**
     * Delete an existing data connector. The connector must be in `draft` state and must not be in use by any workflows or AI agents.
     *
     * @param {Intercom.preview.DeleteDataConnectorRequest} request
     * @param {DataConnectorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     * @throws {@link Intercom.preview.ConflictError}
     *
     * @example
     *     await client.preview.dataConnectors.deleteDataConnector({
     *         id: "12345"
     *     })
     */
    public deleteDataConnector(
        request: Intercom.preview.DeleteDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DeletedDataConnectorObject> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDataConnector(request, requestOptions));
    }

    private async __deleteDataConnector(
        request: Intercom.preview.DeleteDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DeletedDataConnectorObject>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `data_connectors/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Intercom.preview.DeletedDataConnectorObject,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Intercom.preview.ConflictError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/data_connectors/{id}");
    }

    /**
     * Update an existing data connector. Only provided fields are changed. Set `state` to `live` or `draft` to change the connector's state.
     *
     * @param {Intercom.preview.UpdateDataConnectorRequest} request
     * @param {DataConnectorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     * @throws {@link Intercom.preview.ConflictError}
     * @throws {@link Intercom.preview.UnprocessableEntityError}
     *
     * @example
     *     await client.preview.dataConnectors.updateDataConnector({
     *         id: "12345",
     *         name: "Updated Connector Name",
     *         description: "Updated description"
     *     })
     *
     * @example
     *     await client.preview.dataConnectors.updateDataConnector({
     *         id: "12345",
     *         state: "live"
     *     })
     *
     * @example
     *     await client.preview.dataConnectors.updateDataConnector({
     *         id: "12345",
     *         state: "draft"
     *     })
     *
     * @example
     *     await client.preview.dataConnectors.updateDataConnector({
     *         id: "12345",
     *         mock_response: {
     *             "user": {
     *                 "name": "Alice",
     *                 "email": "alice@example.com"
     *             }
     *         }
     *     })
     */
    public updateDataConnector(
        request: Intercom.preview.UpdateDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DataConnectorDetail> {
        return core.HttpResponsePromise.fromPromise(this.__updateDataConnector(request, requestOptions));
    }

    private async __updateDataConnector(
        request: Intercom.preview.UpdateDataConnectorRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DataConnectorDetail>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `data_connectors/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Intercom.preview.DataConnectorDetail, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Intercom.preview.ConflictError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Intercom.preview.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/data_connectors/{id}");
    }

    /**
     * Retrieve paginated execution logs for a specific data connector.
     * Results from the last hour are returned by default. Use `start_ts` and `end_ts` to customize the time range.
     *
     * Request/response bodies are excluded by default. Use `include_bodies=true` to include them.
     *
     * @param {Intercom.preview.ListDataConnectorExecutionResultsRequest} request
     * @param {DataConnectorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.BadRequestError}
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.dataConnectors.listDataConnectorExecutionResults({
     *         data_connector_id: "12345",
     *         per_page: 1,
     *         starting_after: "starting_after",
     *         success: "true",
     *         error_type: "request_configuration_error",
     *         start_ts: 1,
     *         end_ts: 1,
     *         include_bodies: "true"
     *     })
     */
    public listDataConnectorExecutionResults(
        request: Intercom.preview.ListDataConnectorExecutionResultsRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DataConnectorExecutionResultList> {
        return core.HttpResponsePromise.fromPromise(this.__listDataConnectorExecutionResults(request, requestOptions));
    }

    private async __listDataConnectorExecutionResults(
        request: Intercom.preview.ListDataConnectorExecutionResultsRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DataConnectorExecutionResultList>> {
        const {
            data_connector_id: dataConnectorId,
            per_page: perPage,
            starting_after: startingAfter,
            success,
            error_type: errorType,
            start_ts: startTs,
            end_ts: endTs,
            include_bodies: includeBodies,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (perPage != null) {
            _queryParams.per_page = perPage.toString();
        }

        if (startingAfter != null) {
            _queryParams.starting_after = startingAfter;
        }

        if (success != null) {
            _queryParams.success = success;
        }

        if (errorType != null) {
            _queryParams.error_type = errorType;
        }

        if (startTs != null) {
            _queryParams.start_ts = startTs.toString();
        }

        if (endTs != null) {
            _queryParams.end_ts = endTs.toString();
        }

        if (includeBodies != null) {
            _queryParams.include_bodies = includeBodies;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `data_connectors/${core.url.encodePathParam(dataConnectorId)}/execution_results`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Intercom.preview.DataConnectorExecutionResultList,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Intercom.preview.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/data_connectors/{data_connector_id}/execution_results",
        );
    }

    /**
     * Retrieve details for a specific data connector execution result.
     * Always includes request/response bodies and the sanitised request URL.
     *
     * @param {Intercom.preview.ShowDataConnectorExecutionResultRequest} request
     * @param {DataConnectorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Intercom.preview.UnauthorizedError}
     * @throws {@link Intercom.preview.NotFoundError}
     *
     * @example
     *     await client.preview.dataConnectors.showDataConnectorExecutionResult({
     *         data_connector_id: "12345",
     *         id: "99001"
     *     })
     */
    public showDataConnectorExecutionResult(
        request: Intercom.preview.ShowDataConnectorExecutionResultRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): core.HttpResponsePromise<Intercom.preview.DataConnectorExecutionResult> {
        return core.HttpResponsePromise.fromPromise(this.__showDataConnectorExecutionResult(request, requestOptions));
    }

    private async __showDataConnectorExecutionResult(
        request: Intercom.preview.ShowDataConnectorExecutionResultRequest,
        requestOptions?: DataConnectorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Intercom.preview.DataConnectorExecutionResult>> {
        const { data_connector_id: dataConnectorId, id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Intercom-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IntercomEnvironment.UsProduction,
                `data_connectors/${core.url.encodePathParam(dataConnectorId)}/execution_results/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 20) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Intercom.preview.DataConnectorExecutionResult,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Intercom.preview.UnauthorizedError(
                        _response.error.body as Intercom.preview.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Intercom.preview.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IntercomError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/data_connectors/{data_connector_id}/execution_results/{id}",
        );
    }
}
