// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../index.js";

/**
 * A paginated list of data connectors.
 */
export interface DataConnectorList {
    /** The type of object - `list`. */
    type?: "list";
    /** An array of data connector objects. */
    data?: Intercom.preview.DataConnector[];
    /** Pagination information. */
    pages?: DataConnectorList.Pages;
}

export namespace DataConnectorList {
    /**
     * Pagination information.
     */
    export interface Pages {
        type?: "pages";
        /** The number of results per page. */
        per_page?: number;
        /** Cursor for the next page of results. */
        next?: Pages.Next;
    }

    export namespace Pages {
        /**
         * Cursor for the next page of results.
         */
        export interface Next {
            /** The cursor value to use for the next page. */
            starting_after?: string;
        }
    }
}
