// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../index.js";

/**
 * Search using Intercoms Search APIs.
 */
export interface SearchRequest {
    query: SearchRequest.Query;
    pagination?: Intercom.preview.StartingAfterPaging;
}

export namespace SearchRequest {
    export type Query = Intercom.preview.SingleFilterSearchRequest | Intercom.preview.MultipleFilterSearchRequest;
}
