/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssignConversationRequestType = "admin" | "team";

export const AssignConversationRequestType = {
    Admin: "admin",
    Team: "team",
} as const;
