// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../index.js";

/**
 * blocked contact object
 */
export interface ContactBlocked extends Intercom.ContactReference {
    /** Always true. */
    blocked?: boolean;
}
