// This file was auto-generated by Fern from our API Definition.

/**
 * Contains details about the workflow that was triggered and any Custom Data Attributes (CDAs) that were modified during the workflow execution for conversation part type <code>conversation_attribute_updated_by_workflow</code>.
 */
export interface ConversationAttributeUpdatedByWorkflow {
    workflow?: ConversationAttributeUpdatedByWorkflow.Workflow;
    attribute?: ConversationAttributeUpdatedByWorkflow.Attribute;
    value?: ConversationAttributeUpdatedByWorkflow.Value;
}

export namespace ConversationAttributeUpdatedByWorkflow {
    export interface Workflow {
        /** Name of the workflow */
        name?: string;
    }

    export interface Attribute {
        /** Name of the CDA updated */
        name?: string;
    }

    export interface Value {
        /** Value of the CDA updated */
        name?: string;
    }
}
