/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Properties of the attachment files in a conversation part
 */
export interface ConversationAttachmentFiles {
    /** The content type of the file */
    content_type: string;
    /** The base64 encoded file data. */
    data: string;
    /** The name of the file. */
    name: string;
}
