/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Category of the Ticket Type.
 */
export type CreateTicketTypeRequestCategory = "Customer" | "Back-office" | "Tracker";

export const CreateTicketTypeRequestCategory = {
    Customer: "Customer",
    BackOffice: "Back-office",
    Tracker: "Tracker",
} as const;
