/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CustomerRequestIntercomUserId {
    /** The identifier for the contact as given by Intercom. */
    intercom_user_id: string;
}
