// This file was auto-generated by Fern from our API Definition.

/**
 * IP allowlist settings for the workspace.
 */
export interface IpAllowlist {
    /** String representing the object's type. Always has the value `ip_allowlist`. */
    type?: string;
    /** Whether the IP allowlist is enabled for the workspace. */
    enabled?: boolean;
    /**
     * List of allowed IP addresses and/or IP ranges in CIDR notation.
     * Examples:
     * - Single IP: `192.168.0.1`
     * - IP range: `192.168.0.1/24` (allows 192.168.0.0 - 192.168.0.255)
     */
    ip_allowlist?: string[];
}
