/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../index";

/**
 * A list item component that can be rendered in a list.
 */
export interface ListItem {
    /** The type of component you are rendering. */
    type: "item";
    /** A unique identifier for the item. */
    id: string;
    /** The text shown as the title for the item. */
    title: string;
    /** The text shown underneath the item's title. */
    subtitle?: string;
    /** The text shown next to the subtitle, separates by a bullet. */
    tertiary_text?: string;
    /** Rounds the corners of the image. Default is `false`. */
    rounded_image?: boolean;
    /** Styles all list items and prevents the action. Default is `false`. */
    disabled?: boolean;
    /** This can be a Submit Action, URL Action, or Sheets Action. */
    action?: Intercom.ActionComponent;
}
