/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface QuickReplyOption {
    /** The text to display in this quick reply option. */
    text: string;
    /** A unique identifier for this quick reply option. This value will be available within the metadata of the comment conversation part that is created when a user clicks on this reply option. */
    uuid: string;
}
