/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TagCompanyRequestCompaniesItem {
    /** The Intercom defined id representing the company. */
    id?: string;
    /** The company id you have defined for the company. */
    company_id?: string;
}
