/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A URL action opens a given link in a new browser tab.
 */
export interface UrlActionComponent {
    /** The link you want to open. */
    url: string;
}
