// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 1
 *     }
 */
export interface RetrieveArticleRequest {
    /** The unique identifier for the article which is given by Intercom. */
    id: number;
}
