// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../../../index.js";

export type CreateTagRequestBody =
    | Intercom.unstable.CreateOrUpdateTagRequest
    | Intercom.unstable.TagCompanyRequest
    | Intercom.unstable.UntagCompanyRequest
    | Intercom.unstable.TagMultipleUsersRequest;
