/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Intercom from "../../../index";

/**
 * The content source used by AI Agent in the conversation.
 */
export interface ContentSource {
    /** The type of the content source. */
    content_type?: Intercom.ContentSourceContentType;
    /** The internal URL linking to the content source for teammates. */
    url?: string;
    /** The title of the content source. */
    title?: string;
    /** The ISO 639 language code of the content source. */
    locale?: string;
}
