// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../../../index.js";

/**
 * The Internal Articles API is a central place to gather all information and take actions on your internal articles.
 */
export type InternalArticle = Intercom.unstable.InternalArticleListItem;
