// This file was auto-generated by Fern from our API Definition.

import type * as Intercom from "../../../../../index.js";

/**
 * AI-generated topics and subtopics for the conversation.
 */
export interface AiTopics {
    /** Always ai_topics. */
    type?: string;
    /** The list of AI-generated topics for this conversation. */
    topics?: Intercom.preview.AiTopic[];
}
