/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         conversation_id: "123",
 *         display_as: "plaintext"
 *     }
 */
export interface FindConversationRequest {
    /**
     * The id of the conversation to target
     */
    conversation_id: string;
    /**
     * Set to plaintext to retrieve conversation messages in plain text.
     */
    display_as?: string;
}
