// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         created_at_after: 1734519776,
 *         created_at_before: 1734537776
 *     }
 */
export interface CreateDataExportsRequest {
    /** The start date that you request data for. It must be formatted as a unix timestamp. */
    created_at_after: number;
    /** The end date that you request data for. It must be formatted as a unix timestamp. */
    created_at_before: number;
}
