/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const IntercomEnvironment = {
    UsProduction: "https://api.intercom.io",
    EuProduction: "https://api.eu.intercom.io",
    AuProduction: "https://api.au.intercom.io",
} as const;

export type IntercomEnvironment =
    | typeof IntercomEnvironment.UsProduction
    | typeof IntercomEnvironment.EuProduction
    | typeof IntercomEnvironment.AuProduction;
