// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "https://www.example.com"
 *     }
 */
export interface CreateContentImportSourceRequest {
    /** The status of the content import source. */
    status?: CreateContentImportSourceRequest.Status;
    /** The URL of the content import source. */
    url: string;
    /** The unique identifiers for the audiences to associate with this content import source. Can be a single integer or an array of integers. */
    audience_ids?: CreateContentImportSourceRequest.AudienceIds;
}

export namespace CreateContentImportSourceRequest {
    /** The status of the content import source. */
    export const Status = {
        Active: "active",
        Deactivated: "deactivated",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /**
     * The unique identifiers for the audiences to associate with this content import source. Can be a single integer or an array of integers.
     */
    export type AudienceIds = number | number[];
}
