// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteExternalPageRequest {
    /** The unique identifier for the external page which is given by Intercom. */
    id: string;
}
