# .github/workflows/label-ai-generated-prs.yml
name: Label AI-generated PRs

on:
  pull_request:
    types: [opened, edited, synchronize]   # run when the body changes too

jobs:
  call-label-ai-prs:
    uses: intercom/github-action-workflows/.github/workflows/label-ai-prs.yml@main
    secrets: inherit