/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DataAttributesListRequestModel = "contact" | "company" | "conversation";

export const DataAttributesListRequestModel = {
    Contact: "contact",
    Company: "company",
    Conversation: "conversation",
} as const;
