// This file was auto-generated by Fern from our API Definition.

export const DataAttributesListRequestModel = {
    Contact: "contact",
    Company: "company",
    Conversation: "conversation",
} as const;
export type DataAttributesListRequestModel =
    (typeof DataAttributesListRequestModel)[keyof typeof DataAttributesListRequestModel];
